# Generated by Django 2.1.4 on 2018-12-27 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxis_username', models.CharField(blank=True, max_length=200)),
                ('taxis_password', models.CharField(blank=True, max_length=200)),
                ('ika_username', models.CharField(blank=True, max_length=200)),
                ('ika_password', models.CharField(blank=True, max_length=200)),
                ('business_registry_username', models.CharField(blank=True, max_length=200)),
                ('business_registry_password', models.CharField(blank=True, max_length=200)),
                ('tax_number', models.CharField(max_length=200, unique=True)),
                ('social_security_number', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('last_name_2', models.CharField(blank=True, max_length=200)),
                ('father_first_name', models.CharField(blank=True, max_length=200)),
                ('father_last_name', models.CharField(blank=True, max_length=200)),
                ('mother_first_name', models.CharField(blank=True, max_length=200)),
                ('mother_last_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_death', models.DateTimeField(blank=True, null=True)),
                ('country_of_birth', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female')], max_length=2)),
                ('nationality', models.CharField(max_length=200)),
                ('home_phone_number', models.CharField(blank=True, max_length=200)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=200)),
                ('fax', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('identity_type', models.CharField(max_length=200)),
                ('identity_number', models.CharField(max_length=200)),
                ('identity_issue_date', models.CharField(max_length=200)),
                ('identity_issuing_authority', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('municipality', models.CharField(blank=True, max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('marriage_date', models.DateTimeField(blank=True, null=True)),
                ('partner_tax_number', models.CharField(blank=True, max_length=200)),
                ('partner_first_name', models.CharField(blank=True, max_length=200)),
                ('partner_last_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField(blank=True)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
