# Generated by Django 2.1.4 on 2018-12-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxis_username', models.CharField(blank=True, max_length=200)),
                ('taxis_password', models.CharField(blank=True, max_length=200)),
                ('ika_username', models.CharField(blank=True, max_length=200)),
                ('ika_password', models.CharField(blank=True, max_length=200)),
                ('business_registry_username', models.CharField(blank=True, max_length=200)),
                ('business_registry_password', models.CharField(blank=True, max_length=200)),
                ('tax_number', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_first_name', models.CharField(blank=True, max_length=200)),
                ('father_last_name', models.CharField(blank=True, max_length=200)),
                ('mother_first_name', models.CharField(blank=True, max_length=200)),
                ('mother_last_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('date_of_death', models.DateTimeField(blank=True)),
                ('country_of_birth', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female')], max_length=2)),
                ('nationality', models.CharField(max_length=200)),
                ('home_telephone', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=200)),
                ('fax', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('identity_type', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=200)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('provice', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('marriage_date', models.DateTimeField(blank=True)),
                ('partner_tax_number', models.CharField(blank=True, max_length=200)),
                ('partner_first_name', models.CharField(blank=True, max_length=200)),
                ('partner_last_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
