# Generated by Django 2.1.4 on 2018-12-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
