# Generated by Django 2.1.4 on 2018-12-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customer_last_name_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_death',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marriage_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
