# Generated by Django 2.1.4 on 2018-12-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181226_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_death',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marriage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
