# Generated by Django 2.1.4 on 2018-12-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181226_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='home_telephone',
            new_name='home_phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='mobile_phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='provice',
            new_name='municipality',
        ),
    ]
