# Generated by Django 2.1.4 on 2018-12-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181227_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='issue_date',
            new_name='identity_issue_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='issuing_authority',
            new_name='identity_issuing_authority',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='identity_number',
        ),
    ]
